### ISSUE TITLE
I have an issue

### ISSUE THREAD

**Issue by aflah02** [Anindya-Prithvi/dsa-sem2plus#1]
Why you do so much DSA and give other complex GENUINE ISSUE PLS RESPOND :)

**Comment by Anindya-Prithvi** [comment]
![](https://thumbs.gfycat.com/ChubbyLightheartedGoldfish-max-1mb.gif)

**Comment by aflah02** [comment]
<img align="right" alt="GIF" src="https://c.tenor.com/V7-gVNsD2EAAAAAC/michael-scott-the-office.gif" width="250"/>
